from langchain_core.prompts import ChatPromptTemplate          #template bnaanay k liye
from langchain_google_genai import ChatGoogleGenerativeAI      #gemini ki api ko call krne k liye
from langchain_core.output_parsers import JsonOutputParser     #json output ko parse krne k liye
from pydantic import BaseModel, Field                          #Ek strict structure provide krne k liye
from typing import Literal                                     #Ek specific set of values ko allow krne k liye
from dotenv import load_dotenv                                 #api calling
#
load_dotenv()
llm = ChatGoogleGenerativeAI(model = "gemini-2.5-flash", temperature = 0)

class ClassificationOutput(BaseModel):
    category: Literal ["technical", "billing", "general", "urgent"] = Field(
        description = "Category of the support request"
    )

    confidence : float = Field(
        description = "Confidence score between 0.0 and 1.0",
        ge = 0.0,
        le = 1.0
    )
    keywords: list[str] = Field(
        description ="Keywords that determined the classification."
    )

# parser will give the structure according to our scheme
parser = JsonOutputParser(pydantic_object = ClassificationOutput)

#it will classify the prompt {format_instructions will be generated by output parser and rewritten input is invoked}
classify_prompt =ChatPromptTemplate.from_template (""" 
         You are a customer support classifier.
        Classify the following support request into a category.
        {format_instructions}
        Support request: {rewritten_input} """)
 #Inject format instructions into prompt
classify_chain = (
    classify_prompt.partial(format_instructions=parser.get_format_instructions())
    | llm
    | parser
)

if __name__ == "__main__":
    result = classify_chain.invoke({
        "rewritten_input": "Please help me. I am unable to log in to my account."
    })
    print("Classified:", result)
    print("Type:", type(result))