import os
import time
from pypdf import PdfReader
import chromadb
from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from dotenv import load_dotenv

load_dotenv()

# Sahi aur updated models setup
llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash")
embeddings_model = GoogleGenerativeAIEmbeddings(model="models/text-embedding-004")


# ─── STEP 1: PDF CHUNKS (Same as Day 9) ─────────────────────────────────────

def load_pdf_chunks(pdf_path: str, chunk_size: int = 500) -> list[str]:
    reader = PdfReader(pdf_path)
    full_text = ""
    for page in reader.pages:
        full_text += page.extract_text() + "\n"

    words = full_text.split()
    chunks = []
    current_chunk = []
    current_len = 0

    for word in words:
        current_chunk.append(word)
        current_len += len(word) + 1
        if current_len >= chunk_size:
            chunks.append(" ".join(current_chunk))
            current_chunk = []
            current_len = 0

    if current_chunk:
        chunks.append(" ".join(current_chunk))

    return chunks


# ─── STEP 2: CHROMADB DENSE INDEX ───────────────────────────────────────────

def build_dense_index(chunks: list[str]):
    client = chromadb.Client()
    try:
        client.delete_collection("hyde_search")
    except Exception:
        pass

    collection = client.create_collection("hyde_search")
    
    print("Generating vector embeddings for chunks...")
    embeds = embeddings_model.embed_documents(chunks)

    collection.add(
        documents=chunks,
        embeddings=embeds,
        ids=[str(i) for i in range(len(chunks))]
    )
    return collection


# ─── STEP 3: HYPOTHETICAL ANSWER GENERATION ──────────────────────────────────

def generate_hypothetical_answer(query: str) -> str:
    prompt = f"""Answer the following question in 3-4 sentences as if you are
writing a factual passage from a textbook. Be specific and detailed,
even if you are not 100% sure of the answer.

Question: {query}

Answer:"""

    response = llm.invoke(prompt)
    return response.content


# ─── STEP 4: HYDE SEARCH ─────────────────────────────────────────────────────

def hyde_search(query: str, collection, hypothetical_answer: str, top_k: int = 5) -> list[str]:
    # Pass pre-generated answer to save API calls
    hyde_embedding = embeddings_model.embed_query(hypothetical_answer)

    results = collection.query(
        query_embeddings=[hyde_embedding],
        n_results=top_k
    )
    return results["documents"][0]


# ─── STEP 5: NAIVE SEARCH (Baseline Comparison) ─────────────────────────────

def naive_search(query: str, collection, top_k: int = 5) -> list[str]:
    query_embedding = embeddings_model.embed_query(query)
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k
    )
    return results["documents"][0]


# ─── MAIN EXECUTION ──────────────────────────────────────────────────────────

if __name__ == "__main__":
    PDF_PATH = "day09/test.pdf"  # Reusing Day 9 test PDF

    print("PDF load ho rahi hai...")
    chunks = load_pdf_chunks(PDF_PATH)
    print(f"Total chunks created: {len(chunks)}")

    print("\nChromaDB index ban raha hai...")
    collection = build_dense_index(chunks)
    print("Database ready!")

    # Single Test Query
    query = "what is a vector database"
    print(f"\n{'='*50}\nQuery: '{query}'\n{'='*50}")

    # Generate hypothetical answer once and reuse it
    hyp_answer = generate_hypothetical_answer(query)
    print(f"\nHypothetical Answer Generated by LLM:\n{hyp_answer}\n")
    print("-" * 50)

    print("\n--- Naive RAG Result (Direct Query Embedding) ---")
    naive_results = naive_search(query, collection, top_k=1)
    print(naive_results[0][:250] + "...")

    print("\n--- HyDE Result (Hypothetical Answer Embedding) ---")
    hyde_results = hyde_search(query, collection, hyp_answer, top_k=1)
    print(hyde_results[0][:250] + "...")